version: '3'

services:
  db:
    image: postgres:11.2
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/go/src/gitlab.com/oneplanet/corona-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
